### ISSUE TITLE
JavaScript is written inconsistently across lessons

### ISSUE THREAD

**Issue by courtneymorgan** [learn-co-curriculum/javascript-fundamentals-overview#3]
JavaScript is written many ways across all lessons (JavaScript, Javascript, Js, JS)[
![screen shot 2017-06-29 at 4 15 09 pm](https://user-images.githubusercontent.com/29407254/27708232-39e5687e-5ce6-11e7-8455-8fc27a5c4731.png)
](url)

**Comment by jmburges** [comment]
Good catch! We use JS as the abbreviation, and It should be JavaScript throughout. We'll continue to make the changes as we see them.
