### ISSUE TITLE
Inconsistent spelling of JavaScript

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/javascript-fundamentals-overview#4]
In this section, sometimes it's spelled JavaScript and sometimes it's spelled Javascript.

Thanks.

**Comment by ddeleon267** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
